<?php

/**
 * @file
 * WebService Content module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function xtcguzzle_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.xtcguzzle':
      $variables = [
        ':xtcguzzle' => Url::fromRoute('help.page', ['name' => 'xtcguzzle'])->toString(),
      ];

      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The <a href=":xtcguzzle">WebService Content for Guzzle sources</a> module provide features to pull contents from Guzzle source.', $variables) . '</p>';
      $output .= '<h3>' . t('Uses') . '</h3>';
      $output .= '<p>' . t('[to be completed]') . '</p>';

      return $output;
  }
}
